---
- htpasswd:
    create: yes
    path: configs/.htpasswd
#    path: /roles/kibana_nginx-db/tasks/.htpasswd
    name: elk
    password: '55555'
    owner: root
    group: nginx
    mode: 0640
    state: present

- name: Create nginx container for EFK stack
  docker_container:
         name: nginx_ek
         image: nginx:latest 
         state: started
         pull: true
         restart: yes
         restart_policy: unless-stopped
         recreate: yes
         networks:
            - name: shop-socks
         published_ports: 
            - 80:80    
         volumes:
#            - roles/kibana_nginx-db/tasks/nginx.conf:/etc/nginx/nginx.conf
#            - roles/kibana_nginx-db/tasks/.htpasswd:/etc/nginx/.htpasswd
            - configs/nginx.conf:/etc/nginx/nginx.conf
            - configs/.htpasswd:/etc/nginx/.htpasswd
            - nginxdata:/var/log/nginx 
            
- name: Create kibana container for EFK stack
  docker_container:
         name: kibana
         image: docker.elastic.co/kibana/kibana:7.4.2 
         state: started
         pull: true
         restart: yes
         restart_policy: unless-stopped
         recreate: yes
         networks:
            - name: shop-socks
         published_ports: 
            - 5601:5601
         volumes:
            - configs/kibana.yml:/usr/share/kibana/config/kibana.yml
                                                                                                                                                                                                                                                          
- name: Clean up Docker unused images
  docker_prune:
        images: yes
        images_filters
                dangling: true 