---
- htpasswd:
    create: yes
    path: volumes/nginx/.htpasswd
#    path: /roles/kibana_nginx-db/tasks/.htpasswd
    name: efk
    password: '55555'
    owner: root
    group: www-data
    mode: 0640
    state: present

- name: Ensures whether kibana dir exists
  file:
    path: ./volumes/kibana
    state: directory

- name: Ensures whether nginx dir exists
  file:
    path: ./volumes/nginx
    state: directory
                 
- name: Copy nginx config file
  template:
        src: configs/nginx.conf
        dest: ./volumes/nginx
                

- name: Copy kibana config file
  template:
        src: configs/kibana.yml
        dest: ./volumes/kibana

- name: Create kibana container for EFK stack
  docker_container:
         name: kibana
         image: docker.elastic.co/kibana/kibana:7.4.2 
         state: started
         pull: true
         restart: yes
         restart_policy: unless-stopped
         recreate: yes
         networks:
            - name: shop-socks
         published_ports: 
            - 5601:5601
         volumes:
            - ./volumes/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml


- name: Create nginx container for EFK stack
  docker_container:
         name: nginx_ek
         image: nginx:latest 
         state: started
         pull: true
         restart: yes
         restart_policy: unless-stopped
         recreate: yes
         networks:
            - name: shop-socks
         published_ports: 
            - 80:80    
         volumes:
#            - roles/kibana_nginx-db/tasks/nginx.conf:/etc/nginx/nginx.conf
#            - roles/kibana_nginx-db/tasks/.htpasswd:/etc/nginx/.htpasswd
            - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./volumes/nginx/.htpasswd:/etc/nginx/.htpasswd
            - nginxdata:/var/log/nginx 
                                                                                                                                                                                                                                                                  
- name: Clean up Docker unused images
  docker_prune:
        images: yes
        images_filters:
                dangling: true 