filebeat.inputs:
- type: log
  paths:
      - /var/log/syslog
#      - /var/log/auth.log

- type: container
  paths: 
        - '/var/lib/docker/containers/*/*.log'

processors:
- add_docker_metadata: 
        host: "unix:///var/run/docker.sock"
- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true
    
output.elasticsearch:
    hosts: ["elasticsearch:9200"]
    indices:
        - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"


logging.json: true
logging.metrics.enabled: false

logging.level: info
logging.to_files: false
logging.to_syslog: false
loggins.metrice.enabled: false
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
ssl.verification_mode: none          